[package]
name = "async-lsp-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35.1", features = ["io-util", "rt", "process"] }
tower-lsp = "0.20.0"
serde = "1.0.204"
serde_json = "1.0.111"
tracing = "0.1.40"
